# Workflow to lint and test code when pushed to master branch
# and then set up DVC if all tests pass
name: Python package

# Controls when the action will run. 
on:
  # Triggers the workflow on push to master branch
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install scikit-learn pandas numpy pytest jupyter jupyterlab fastapi flake8

    - name: Run linting
      run: |
        flake8 --ignore=E501,E402,E226,E231 .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - uses: iterative/setup-dvc@v1

    - name: DVC pull
      run: |
        dvc pull --remote s3remote

    - name: Run testing
      run: |
        pytest